# -*- coding: utf-8

# -*- coding: utf-8

import os
import argparse

import snakeski.workflows as w
from snakeski.workflows import WorkflowSuperClass


workflow_object = WorkflowSuperClass(argparse.Namespace(config=config))
workflow_object.init('hg19_core_dryclean')

rule hg19_core_pipeline_target_rule:
    input: workflow_object.target_files


for _subworkflow in workflow_object.tasks:
    _include = os.path.join(w.get_path_to_workflows_dir(),
                          _subworkflow,
                          'Snakefile')
    include: _include
