# -*- coding: utf-8

import os
import argparse

from snakeski.workflows.hg19_core_dryclean import hg19CoreDrycleanWorkflow
import snakeski.workflows as w


hg19_core_dryclean_workflow_object = hg19CoreDrycleanWorkflow(argparse.Namespace(config=config)

rule hg19_core_pipeline_target_rule:
    input: hg19_core_dryclean_workflow_object.target_files


for _subworkflow in hg19_core_dryclean_workflow_object.subworkflows:
    include: os.path.join(w.get_path_to_workflows_dir(),
                          _subworkflow,
                          'Snakefile')
